---
# tasks file for roles/bastion
- name: install packages
  apt:
    pkg:
    - git
    - ansible
    - python3
    update_cache: yes
  become: true

- name: Copy ssh private key to root
  shell:
    cmd: "cp /home/{{ ssh_ansible_user }}/.ssh/id_rsa /root/.ssh/"
  become: true
