---
# tasks file for roles/prometheus
- name: update and install prometheus
  apt:
    pkg:
    - prometheus
    update_cache: yes

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
  become: true
