---
# tasks file for roles/kibana
- name: APT - Add elastic repo key
  apt_key: url="http://elasticrepo.serveradmin.ru/elastic.asc"

- name: Add repo to source list
  template: src=kibana.list.j2 dest=/etc/apt/sources.list.d/kibana.list
  become: true

- name: Install kibana
  apt: name=kibana update_cache=yes
  become: true

- name: Copy config
  template: src=kibanaConf.j2 dest=/etc/kibana/kibana.yml
 
- name: Force systemd to reread configs
  systemd: daemon_reload=yes
  become: true
 
- name: Enable kibana.service
  systemd:
    name: kibana.service
    enabled: yes
  become: true
 
- name: Start kibana.service
  systemd: name=kibana.service state=restarted
  become: true

- name: mkdir for certs
  ansible.builtin.file:
    path: /etc/kibana/certs/
    state: directory
    mode: '0745'

- name: Touch a file certs
  ansible.builtin.file:
    path: /etc/kibana/certs/http_ca.crt
    state: touch
    mode: '0660'

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /etc/kibana/certs
    state: directory
    recurse: yes
    owner: root
    group: kibana
