---
# tasks file for roles/logstash
- name: APT - Add elastic repo key
  apt_key: url="http://elasticrepo.serveradmin.ru/elastic.asc"

- name: Add repo to source list
  template: src=logstash.list.j2 dest=/etc/apt/sources.list.d/logstash.list
  become: true

- name: Install Logstash
  apt: name=logstash state=present force=true update_cache=yes

- name: Copy logstash input.conf
  template: src=input.conf.j2 dest=/etc/logstash/conf.d/input.conf

- name: Copy logstash output.conf
  template: src=output.conf.j2 dest=/etc/logstash/conf.d/output.conf

- name: Copy logstash filter.conf
  template: src=filter.conf.j2 dest=/etc/logstash/conf.d/filter.conf

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Enable logstash.service
  systemd:
    name: logstash.service
    enabled: yes

- name: Start logstash.service
  systemd: name=logstash.service state=restarted
  become: true
